# Generated by Django 3.1 on 2020-09-13 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='Mobile Number')),
                ('name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Organizer')),
                ('activation_key', models.CharField(blank=True, max_length=64, verbose_name='Activation Key')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('additional', models.JSONField(default=dict)),
                ('avatar', models.ImageField(default='static/avatars/user.jpg', upload_to='static/avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', home.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=200, verbose_name='Line 1')),
                ('line2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Line 2 (Optional)')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('pincode', models.CharField(max_length=10, verbose_name='Pincode')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('name', models.CharField(max_length=250, verbose_name='Event Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('details', models.TextField(verbose_name='Details')),
                ('category', models.JSONField(default=list)),
                ('start_date', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Event Start Date')),
                ('end_date', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Event End Date')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Fees')),
                ('sport', models.CharField(max_length=250, verbose_name='Sport')),
                ('duration', models.CharField(max_length=250, verbose_name='Duration')),
                ('rules', models.TextField(verbose_name='Rules')),
                ('prizes', models.JSONField(default=dict)),
                ('venue', models.TextField(verbose_name='Venue')),
                ('is_team', models.BooleanField(default=False, verbose_name='Team Registration')),
                ('is_individual', models.BooleanField(default=False, verbose_name='Individual Registration')),
                ('accept_registration', models.BooleanField(default=False, verbose_name='Accept Registration')),
                ('fixtures', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Team Name')),
                ('category', models.JSONField(default=list)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ManyToManyField(blank=True, related_name='Team_Member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Date To Complete')),
                ('interests', models.JSONField(default=list)),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('address', models.ManyToManyField(blank=True, to='home.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(blank=True, max_length=200, verbose_name='Order ID')),
                ('paymentid', models.CharField(blank=True, max_length=200, verbose_name='Payment ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('mode', models.CharField(blank=True, max_length=20, verbose_name='Mode')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Net')),
                ('other_fields', models.JSONField(default=dict)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Organizer Name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='Mobile Number')),
                ('category', models.JSONField(default=list)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('address', models.ManyToManyField(blank=True, to='home.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.team')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.organizer'),
        ),
    ]
