# Generated by Django 3.1.1 on 2020-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_forgetpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(max_length=12, verbose_name='Date To Complete'),
        ),
    ]
