# Generated by Django 3.1.1 on 2020-09-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200928_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.CharField(default=None, max_length=10, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.CharField(default=None, max_length=10, verbose_name='Weight'),
        ),
    ]
